[package]
name = "bricks"
version = "0.1.0"
edition = "2021"
authors = ["s3l4h"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
rayon = "1.3"
indicatif = {version = "*", features = ["rayon"]}
